### ISSUE TITLE
No "Countdown Timer" in Docks

### ISSUE THREAD

**Issue by kuoman** [ashmanix/obs-plugin-countdown#29] opened 2023-06-27 20:52 UTC
Running on a Mac (Ventura 13.4.1 - M1 Max) and OBS (29.1.3 - 64 bit). I've run the ARM installer and verified that the obs-plugin-countdown.plugin is installed in the plugins folder.  When I run OBS I do not see "Countdown Timer" listed in the "Docks" menu with or w/o a Text(freetype 2) selected (or created). No more OBS Text Source option is available.

**Comment by ashmanix** [comment] 2023-06-27 21:52
I have this running on my M1 MacBook with OBS v29.1.3 on MacOS Ventura 13.4.1.

What specific folder has the plugin been loaded into?

Can you do the following steps:
- Can you check the logs when OBS opens (go to `Help->Log Files->View Current Log`) to see what the logs say. 

- Can you look for any logs that have `[obs-plugin-countdown]` listed on them like 
`22:48:54.878: [obs-plugin-countdown] plugin loaded successfully (version 1.3.0)`

Can you see any logs that indicate a failure in the plugin loading (or if the plugin successfully loads)?

**Comment by vecocamacho** [comment] 2023-07-11 14:25
I have a similar problem except that if I go to: (/Applications/OBS.app/Contents/PlugIns) there is no obs-plugin-countdown installed, I have try different versions and nothing (obs-plugin-countdown 1.3.0, obs-plugin-countdown 1.2.0, obs-plugin-countdown 1.1.0, obs-plugin-countdown 1.0.1) installer says that the app has been installed but no folder, and of course nothing under docks

MacBook Pro 13-inch Mid 2012 - macOS Ventura 13.4.1
OBS Studio 29.1.3 (64 bit)

Current log:

08:21:20.906: 	restart_on_activate:     yes
08:21:20.906: 	close_when_inactive:     yes
08:21:20.906: 	full_decode:             no
08:21:20.906: 	ffmpeg_options:          
08:21:20.910: Switched to scene '--Branded--'
08:21:20.910: ------------------------------------------------
08:21:20.910: Loaded scenes:
08:21:20.910: - scene '--Branded--':
08:21:20.910:     - source: 'FaceTime HD' (av_capture_input_v2)
08:21:20.910:         - filter: 'HDR' (color_filter_v2)
08:21:20.910:     - source: 'Lower 3rds' (browser_source)
08:21:20.910:     - source: 'Mic' (coreaudio_input_capture)
08:21:20.910:     - source: 'Beep' (ffmpeg_source)
08:21:20.910: ------------------------------------------------
08:21:31.024: User added source 'Timer test' (text_ft2_source_v2) to scene '--Branded--'
08:21:41.340: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Beep)
08:21:41.340:

**Comment by vecocamacho** [comment] 2023-07-11 14:53
Ok so, I solved it, the problem is where the plugin is being installed by default 

It should be on 

/Applications/OBS.app/Contents/PlugIns/obs-plugin-countdown.plugin

Instead of

/Library/Application Support/obs-studio/plugins/obs-plugin-countdown.plugin

FIX: Just copy and paste

**Comment by vecocamacho** [comment] 2023-07-11 14:57
Ok so, I solved it, the problem is where the plugin is being installed by default

It should be on

/Applications/OBS.app/Contents/PlugIns/obs-plugin-countdown.plugin

Instead of

/Library/Application Support/obs-studio/plugins/obs-plugin-countdown.plugin

FIX: Just copy and paste

**Comment by ashmanix** [comment] 2023-07-11 20:19
> Running on a Mac (Ventura 13.4.1 - M1 Max) and OBS (29.1.3 - 64 bit). I've run the ARM installer and verified that the obs-plugin-countdown.plugin is installed in the plugins folder. When I run OBS I do not see "Countdown Timer" listed in the "Docks" menu with or w/o a Text(freetype 2) selected (or created). No more OBS Text Source option is available.

@kuoman were you able to get any more info on this issue from the logs?

**Comment by ashmanix** [comment] 2023-07-25 11:03
Closing this issue.

**Closed by ashmanix** 2023-07-25 11:03 UTC
